apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akash-guard.fullname" . }}
  namespace: {{ include "akash-guard.namespace" . }}
  labels:
    {{- include "akash-guard.labels" . | nindent 4 }}
