// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcEgressPktCounters struct {
	_           structs.HostLayout
	Packets     uint64
	Bytes       uint64
	SynPackets  uint64
	Port25Conns uint64
}

type TcEgressRatelimitState struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Pad     uint32
	Tokens  uint64
	LastNs  uint64
	RateBps uint64
	Burst   uint64
}

// LoadTcEgress returns the embedded CollectionSpec for TcEgress.
func LoadTcEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcEgress: %w", err)
	}

	return spec, err
}

// LoadTcEgressObjects loads TcEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcEgressObjects
//	*TcEgressPrograms
//	*TcEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressSpecs struct {
	TcEgressProgramSpecs
	TcEgressMapSpecs
	TcEgressVariableSpecs
}

// TcEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressProgramSpecs struct {
	TcEgress *ebpf.ProgramSpec `ebpf:"tc_egress"`
}

// TcEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressMapSpecs struct {
	Counters       *ebpf.MapSpec `ebpf:"counters"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	IfaceRatelimit *ebpf.MapSpec `ebpf:"iface_ratelimit"`
}

// TcEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressVariableSpecs struct {
}

// TcEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressObjects struct {
	TcEgressPrograms
	TcEgressMaps
	TcEgressVariables
}

func (o *TcEgressObjects) Close() error {
	return _TcEgressClose(
		&o.TcEgressPrograms,
		&o.TcEgressMaps,
	)
}

// TcEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressMaps struct {
	Counters       *ebpf.Map `ebpf:"counters"`
	Events         *ebpf.Map `ebpf:"events"`
	IfaceRatelimit *ebpf.Map `ebpf:"iface_ratelimit"`
}

func (m *TcEgressMaps) Close() error {
	return _TcEgressClose(
		m.Counters,
		m.Events,
		m.IfaceRatelimit,
	)
}

// TcEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressVariables struct {
}

// TcEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressPrograms struct {
	TcEgress *ebpf.Program `ebpf:"tc_egress"`
}

func (p *TcEgressPrograms) Close() error {
	return _TcEgressClose(
		p.TcEgress,
	)
}

func _TcEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcegress_bpfeb.o
var _TcEgressBytes []byte
