package ebpf

import (
	"context"
	"encoding/binary"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// PktEvent mirrors the C struct pkt_event from tc_egress.c.
type PktEvent struct {
	Ifindex  uint32
	DstIP    uint32
	Proto    uint8
	_        [1]byte
	DstPort  uint16
	TCPFlags uint8
	_        [3]byte
}

// IfaceStats holds aggregated per-interface statistics over a time window.
type IfaceStats struct {
	Ifindex      uint32
	Namespace    string
	PodName      string
	Packets      uint64
	Bytes        uint64
	SYNPackets   uint64
	Port25Conns  uint64
	UniqueDstIPs map[uint32]struct{}
}

// Monitor loads the TC eBPF program, attaches it to pod veth interfaces,
// and exposes aggregated stats per interface.
type Monitor struct {
	objs      tcEgressObjects
	mu        sync.RWMutex
	stats     map[uint32]*IfaceStats // keyed by ifindex
	links     map[uint32]link.Link
	ifaceInfo map[uint32]ifaceMeta   // ifindex → namespace/pod
}

type ifaceMeta struct {
	namespace string
	podName   string
}

// tcEgressObjects is generated by bpf2go. Until code generation runs,
// we define a stub so the package compiles. Remove this once
// `go generate ./bpf/` has been run.
type tcEgressObjects struct {
	TcEgress *ebpf.Program
	Counters *ebpf.Map
	Events   *ebpf.Map
}

func (o *tcEgressObjects) Close() {}

func NewMonitor() *Monitor {
	return &Monitor{
		stats:     make(map[uint32]*IfaceStats),
		links:     make(map[uint32]link.Link),
		ifaceInfo: make(map[uint32]ifaceMeta),
	}
}

// Load loads the compiled eBPF object. Must be called before Run.
func (m *Monitor) Load() error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}
	// bpf2go-generated load function: loadTcEgressObjects(&m.objs, nil)
	// Uncomment after running `go generate ./bpf/`:
	// return loadTcEgressObjects(&m.objs, nil)
	slog.Warn("eBPF objects not yet generated — run `go generate ./bpf/` first")
	return nil
}

// Run starts the veth watcher and ring buffer consumer. Blocks until ctx done.
func (m *Monitor) Run(ctx context.Context) {
	go m.watchVeths(ctx)
	if m.objs.Events != nil {
		go m.consumeRingBuf(ctx)
	}
	<-ctx.Done()
}

// watchVeths polls /sys/class/net for veth interfaces that belong to pods
// (identified by the symlink target containing "pods" or by checking
// the peer namespace via /proc).
func (m *Monitor) watchVeths(ctx context.Context) {
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			m.syncVeths(ctx)
		}
	}
}

func (m *Monitor) syncVeths(ctx context.Context) {
	ifaces, err := net.Interfaces()
	if err != nil {
		slog.Error("list interfaces", "err", err)
		return
	}

	active := make(map[uint32]struct{})
	for _, iface := range ifaces {
		// Pod veth interfaces on the host side follow a "veth" prefix convention.
		if !strings.HasPrefix(iface.Name, "veth") {
			continue
		}
		idx := uint32(iface.Index)
		active[idx] = struct{}{}

		m.mu.Lock()
		if _, exists := m.links[idx]; !exists {
			meta := m.resolveIfaceMeta(iface.Name)
			m.ifaceInfo[idx] = meta
			m.stats[idx] = &IfaceStats{
				Ifindex:      idx,
				Namespace:    meta.namespace,
				PodName:      meta.podName,
				UniqueDstIPs: make(map[uint32]struct{}),
			}
			if m.objs.TcEgress != nil {
				if err := m.attachTC(ctx, iface, idx); err != nil {
					slog.Warn("attach TC failed", "iface", iface.Name, "err", err)
				}
			}
			slog.Info("tracking veth", "iface", iface.Name, "ifindex", idx,
				"namespace", meta.namespace, "pod", meta.podName)
		}
		m.mu.Unlock()
	}

	// Detach and remove interfaces that no longer exist.
	m.mu.Lock()
	for idx, l := range m.links {
		if _, ok := active[idx]; !ok {
			l.Close()
			delete(m.links, idx)
			delete(m.stats, idx)
			delete(m.ifaceInfo, idx)
		}
	}
	m.mu.Unlock()
}

func (m *Monitor) attachTC(_ context.Context, iface net.Interface, idx uint32) error {
	// Attach TC egress hook using cilium/ebpf link package.
	// The generated program is stored in m.objs.TcEgress.
	// l, err := link.AttachTCX(link.TCXOptions{
	// 	Interface: iface.Index,
	// 	Program:   m.objs.TcEgress,
	// 	Attach:    ebpf.AttachTCXEgress,
	// })
	// if err != nil { return err }
	// m.links[idx] = l
	_ = idx
	_ = iface
	return nil
}

// resolveIfaceMeta attempts to resolve namespace and pod name for a veth
// by reading the Kubernetes pod network namespace symlinks under /var/run/netns
// or by inspecting /proc/<pid>/net/if_inet6.
// Falls back to "unknown" if not resolvable.
func (m *Monitor) resolveIfaceMeta(ifaceName string) ifaceMeta {
	// Look for a matching pod annotation under /var/run/netns/<ns>_<pod>
	// This is a best-effort heuristic; real resolution may require the
	// CRI socket or the k8s API for a complete mapping.
	netnsDir := "/var/run/netns"
	entries, err := os.ReadDir(netnsDir)
	if err != nil {
		return ifaceMeta{namespace: "unknown", podName: ifaceName}
	}

	for _, e := range entries {
		// Convention: some CNIs name netns files as <namespace>_<pod>
		parts := strings.SplitN(e.Name(), "_", 2)
		if len(parts) == 2 {
			// Check if this netns contains our ifindex via symlink inspection.
			symlink, err := os.Readlink(filepath.Join(netnsDir, e.Name()))
			if err != nil || symlink == "" {
				continue
			}
			_ = parts // namespace=parts[0], pod=parts[1]
		}
	}
	return ifaceMeta{namespace: "unknown", podName: ifaceName}
}

// consumeRingBuf reads packet events from the eBPF ring buffer and
// updates unique-dst-IP sets per interface.
func (m *Monitor) consumeRingBuf(ctx context.Context) {
	rd, err := ringbuf.NewReader(m.objs.Events)
	if err != nil {
		slog.Error("ringbuf reader", "err", err)
		return
	}
	defer rd.Close()

	go func() {
		<-ctx.Done()
		rd.Close()
	}()

	for {
		rec, err := rd.Read()
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			slog.Error("ringbuf read", "err", err)
			continue
		}
		if len(rec.RawSample) < int(unsafe.Sizeof(PktEvent{})) {
			continue
		}
		ev := (*PktEvent)(unsafe.Pointer(&rec.RawSample[0]))
		dstIP := binary.BigEndian.Uint32((*[4]byte)(unsafe.Pointer(&ev.DstIP))[:])

		m.mu.Lock()
		if s, ok := m.stats[ev.Ifindex]; ok {
			s.UniqueDstIPs[dstIP] = struct{}{}
		}
		m.mu.Unlock()
	}
}

// Snapshot returns a copy of current stats for all tracked interfaces.
func (m *Monitor) Snapshot() []*IfaceStats {
	m.mu.RLock()
	defer m.mu.RUnlock()

	out := make([]*IfaceStats, 0, len(m.stats))
	for _, s := range m.stats {
		// Deep copy unique dst IPs map.
		dstCopy := make(map[uint32]struct{}, len(s.UniqueDstIPs))
		for ip := range s.UniqueDstIPs {
			dstCopy[ip] = struct{}{}
		}
		cp := *s
		cp.UniqueDstIPs = dstCopy

		// Merge percpu map values from the kernel.
		if m.objs.Counters != nil {
			if err := mergeCounters(m.objs.Counters, s.Ifindex, &cp); err != nil {
				slog.Warn("merge counters", "ifindex", s.Ifindex, "err", err)
			}
		}
		out = append(out, &cp)
	}
	return out
}

// ResetWindow clears the per-window state for all tracked interfaces.
func (m *Monitor) ResetWindow() {
	m.mu.Lock()
	defer m.mu.Unlock()
	for idx, s := range m.stats {
		s.Packets = 0
		s.Bytes = 0
		s.SYNPackets = 0
		s.Port25Conns = 0
		s.UniqueDstIPs = make(map[uint32]struct{})
		// Zero the kernel-side percpu map entry.
		if m.objs.Counters != nil {
			_ = m.objs.Counters.Delete(idx)
		}
	}
}

// mergeCounters reads a PERCPU_HASH entry and sums values across CPUs.
func mergeCounters(m *ebpf.Map, ifindex uint32, s *IfaceStats) error {
	type pktCounters struct {
		Packets     uint64
		Bytes       uint64
		SYNPackets  uint64
		Port25Conns uint64
	}
	var perCPU []pktCounters
	if err := m.Lookup(ifindex, &perCPU); err != nil {
		return err
	}
	for _, c := range perCPU {
		s.Packets += c.Packets
		s.Bytes += c.Bytes
		s.SYNPackets += c.SYNPackets
		s.Port25Conns += c.Port25Conns
	}
	return nil
}
